<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210513163543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA almoxarifado');
        $this->addSql('ALTER TABLE cautela.itens_cautela DROP CONSTRAINT fk_671109e570b4a1cf');
        $this->addSql('ALTER TABLE cautela.historicos DROP CONSTRAINT fk_194e14abe308ac6f');
        $this->addSql('ALTER TABLE cautela.itens_cautela DROP CONSTRAINT fk_671109e5e308ac6f');
        $this->addSql('ALTER TABLE material.armas DROP CONSTRAINT fk_c03a91cec415fce0');
        $this->addSql('ALTER TABLE material.modelos_armas DROP CONSTRAINT fk_bf85ab38c415fce0');
        $this->addSql('ALTER TABLE pessoal.justificativas DROP CONSTRAINT fk_f7f982c23799346e');
        $this->addSql('ALTER TABLE pessoal.usuarios DROP CONSTRAINT fk_f2f4da252b32db58');
        $this->addSql('ALTER TABLE geral.unidades DROP CONSTRAINT fk_9206b59298a62f9b');
        $this->addSql('ALTER TABLE pessoal.usuarios DROP CONSTRAINT fk_f2f4da252be8a956');
        $this->addSql('ALTER TABLE pessoal.usuarios DROP CONSTRAINT fk_f2f4da25d2d890d2');
        $this->addSql('ALTER TABLE material.celulares_funcionais DROP CONSTRAINT fk_42dae5da7b00651c');
        $this->addSql('ALTER TABLE material.radios_ht DROP CONSTRAINT fk_aa4e4f137b00651c');
        $this->addSql('ALTER TABLE material.materiais DROP CONSTRAINT fk_c77516b67b00651c');
        $this->addSql('ALTER TABLE material.impressoras DROP CONSTRAINT fk_db29b037b00651c');
        $this->addSql('ALTER TABLE material.talonarios DROP CONSTRAINT fk_9e15f5b7b00651c');
        $this->addSql('ALTER TABLE material.notebooks DROP CONSTRAINT fk_9651bf977b00651c');
        $this->addSql('ALTER TABLE material.etilometros DROP CONSTRAINT fk_ded6d7427b00651c');
        $this->addSql('ALTER TABLE material.armas DROP CONSTRAINT fk_c03a91ce6bf700bd');
        $this->addSql('ALTER TABLE material.coletes DROP CONSTRAINT fk_ddb49cbd7b00651c');
        $this->addSql('ALTER TABLE material.algemas DROP CONSTRAINT fk_ccf493d06bf700bd');
        $this->addSql('ALTER TABLE pessoal.usuarios DROP CONSTRAINT fk_f2f4da25ccfa12b8');
        $this->addSql('ALTER TABLE material.coletes DROP CONSTRAINT fk_ddb49cbdf81ea286');
        $this->addSql('ALTER TABLE material.armas DROP CONSTRAINT fk_c03a91ce9e862afd');
        $this->addSql('ALTER TABLE material.celulares_funcionais DROP CONSTRAINT fk_42dae5daaa7b2f5c');
        $this->addSql('ALTER TABLE material.radios_ht DROP CONSTRAINT fk_aa4e4f13aa7b2f5c');
        $this->addSql('ALTER TABLE material.municoes DROP CONSTRAINT fk_2cde7639aa7b2f5c');
        $this->addSql('ALTER TABLE material.materiais DROP CONSTRAINT fk_c77516b6aa7b2f5c');
        $this->addSql('ALTER TABLE material.impressoras DROP CONSTRAINT fk_db29b03aa7b2f5c');
        $this->addSql('ALTER TABLE material.talonarios DROP CONSTRAINT fk_9e15f5baa7b2f5c');
        $this->addSql('ALTER TABLE material.acessorios DROP CONSTRAINT fk_59d97fc4aa7b2f5c');
        $this->addSql('ALTER TABLE material.notebooks DROP CONSTRAINT fk_9651bf97aa7b2f5c');
        $this->addSql('ALTER TABLE material.etilometros DROP CONSTRAINT fk_ded6d742aa7b2f5c');
        $this->addSql('ALTER TABLE material.armas DROP CONSTRAINT fk_c03a91ced62c8297');
        $this->addSql('ALTER TABLE material.item_arma DROP CONSTRAINT fk_f66807ddaa7b2f5c');
        $this->addSql('ALTER TABLE material.coletes DROP CONSTRAINT fk_ddb49cbdaa7b2f5c');
        $this->addSql('ALTER TABLE material.algemas DROP CONSTRAINT fk_ccf493d0d62c8297');
        $this->addSql('ALTER TABLE cautela.cautelas DROP CONSTRAINT fk_51987be8e132a3e7');
        $this->addSql('ALTER TABLE material.armas DROP CONSTRAINT fk_c03a91ce1ddc7b11');
        $this->addSql('ALTER TABLE cautela.historicos DROP CONSTRAINT fk_194e14ab60da4051');
        $this->addSql('ALTER TABLE pessoal.usuarios DROP CONSTRAINT fk_f2f4da25e99a6e1d');
        $this->addSql('ALTER TABLE pessoal.usuarios DROP CONSTRAINT fk_f2f4da2595bb8cf7');
        $this->addSql('ALTER TABLE cautela.cautelas DROP CONSTRAINT fk_51987be819bd774c');
        $this->addSql('ALTER TABLE cautela.cautelas DROP CONSTRAINT fk_51987be8db38439e');
        $this->addSql('ALTER TABLE pessoal.frequencias DROP CONSTRAINT fk_259df6c0db38439e');
        $this->addSql('ALTER TABLE cautela.historicos DROP CONSTRAINT fk_194e14abdb38439e');
        $this->addSql('ALTER TABLE cautela.historicos DROP CONSTRAINT fk_194e14ab19bd774c');
        $this->addSql('ALTER TABLE pessoal.contatos DROP CONSTRAINT fk_7f1d36cbb564fbc1');
        $this->addSql('ALTER TABLE pessoal.contatos DROP CONSTRAINT fk_7f1d36cbfa0a674b');
        $this->addSql('ALTER TABLE cautela.cautelas DROP CONSTRAINT fk_51987be871e74549');
        $this->addSql('ALTER TABLE material.armas DROP CONSTRAINT fk_c03a91cebecf282a');
        $this->addSql('ALTER TABLE material.celulares_funcionais DROP CONSTRAINT fk_42dae5da81f64efa');
        $this->addSql('ALTER TABLE material.radios_ht DROP CONSTRAINT fk_aa4e4f1381f64efa');
        $this->addSql('ALTER TABLE material.municoes DROP CONSTRAINT fk_2cde763981f64efa');
        $this->addSql('ALTER TABLE material.materiais DROP CONSTRAINT fk_c77516b681f64efa');
        $this->addSql('ALTER TABLE material.impressoras DROP CONSTRAINT fk_db29b0381f64efa');
        $this->addSql('ALTER TABLE material.talonarios DROP CONSTRAINT fk_9e15f5b81f64efa');
        $this->addSql('ALTER TABLE material.acessorios DROP CONSTRAINT fk_59d97fc4e4360615');
        $this->addSql('ALTER TABLE material.notebooks DROP CONSTRAINT fk_9651bf9781f64efa');
        $this->addSql('ALTER TABLE material.etilometros DROP CONSTRAINT fk_ded6d74281f64efa');
        $this->addSql('ALTER TABLE material.armas DROP CONSTRAINT fk_c03a91cee4360615');
        $this->addSql('ALTER TABLE material.item_arma DROP CONSTRAINT fk_f66807dd81f64efa');
        $this->addSql('ALTER TABLE material.coletes DROP CONSTRAINT fk_ddb49cbd81f64efa');
        $this->addSql('ALTER TABLE material.algemas DROP CONSTRAINT fk_ccf493d0e4360615');
        $this->addSql('ALTER TABLE material.celulares_funcionais DROP CONSTRAINT fk_42dae5da44f8a1d3');
        $this->addSql('ALTER TABLE material.radios_ht DROP CONSTRAINT fk_aa4e4f1344f8a1d3');
        $this->addSql('ALTER TABLE material.materiais DROP CONSTRAINT fk_c77516b644f8a1d3');
        $this->addSql('ALTER TABLE material.impressoras DROP CONSTRAINT fk_db29b0344f8a1d3');
        $this->addSql('ALTER TABLE material.talonarios DROP CONSTRAINT fk_9e15f5b44f8a1d3');
        $this->addSql('ALTER TABLE material.acessorios DROP CONSTRAINT fk_59d97fc4edf4b99b');
        $this->addSql('ALTER TABLE material.notebooks DROP CONSTRAINT fk_9651bf9744f8a1d3');
        $this->addSql('ALTER TABLE material.etilometros DROP CONSTRAINT fk_ded6d74244f8a1d3');
        $this->addSql('ALTER TABLE material.armas DROP CONSTRAINT fk_c03a91ceedf4b99b');
        $this->addSql('ALTER TABLE pessoal.usuarios DROP CONSTRAINT fk_f2f4da259a6508a3');
        $this->addSql('ALTER TABLE material.coletes DROP CONSTRAINT fk_ddb49cbd44f8a1d3');
        $this->addSql('ALTER TABLE material.algemas DROP CONSTRAINT fk_ccf493d0edf4b99b');
        $this->addSql('DROP SEQUENCE message_seq CASCADE');
        $this->addSql('DROP SEQUENCE usuarios_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.materiais_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.celulares_funcionais_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.radios_ht_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.municoes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.impressoras_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.calibre_armas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.talonarios_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.acessorios_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.notebooks_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.etilometros_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.destinos_material_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.status_material_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.armas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.tipo_material_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.tipos_armas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.item_arma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.tipos_colete_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.modelos_armas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.coletes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.marcas_armas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE material.algemas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.situacoes_policiais_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.faltas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.sexos_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.permissoes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.justificativas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.graduacoes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.frequencias_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.tipos_sanguineos_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.estados_civis_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.contatos_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.escolaridades_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pessoal.profiles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cautela.cautelas_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cautela.itens_cautela_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cautela.historicos_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE geral.comandos_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE geral.setores_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE geral.unidades_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE almoxarifado.produtos_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE almoxarifado.produtos (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('DROP TABLE material.celulares_funcionais');
        $this->addSql('DROP TABLE pessoal.situacoes_policiais');
        $this->addSql('DROP TABLE material.radios_ht');
        $this->addSql('DROP TABLE cautela.cautelas');
        $this->addSql('DROP TABLE material.municoes');
        $this->addSql('DROP TABLE material.materiais');
        $this->addSql('DROP TABLE material.calibre_armas');
        $this->addSql('DROP TABLE pessoal.faltas');
        $this->addSql('DROP TABLE material.impressoras');
        $this->addSql('DROP TABLE material.talonarios');
        $this->addSql('DROP TABLE pessoal.sexos');
        $this->addSql('DROP TABLE material.acessorios');
        $this->addSql('DROP TABLE pessoal.permissoes');
        $this->addSql('DROP TABLE material.notebooks');
        $this->addSql('DROP TABLE material.etilometros');
        $this->addSql('DROP TABLE pessoal.frequencias');
        $this->addSql('DROP TABLE pessoal.graduacoes');
        $this->addSql('DROP TABLE pessoal.justificativas');
        $this->addSql('DROP TABLE geral.comandos');
        $this->addSql('DROP TABLE pessoal.tipos_sanguineos');
        $this->addSql('DROP TABLE pessoal.estados_civis');
        $this->addSql('DROP TABLE material.status_material');
        $this->addSql('DROP TABLE material.armas');
        $this->addSql('DROP TABLE cautela.historicos');
        $this->addSql('DROP TABLE pessoal.profiles');
        $this->addSql('DROP TABLE pessoal.contatos');
        $this->addSql('DROP TABLE material.tipos_colete');
        $this->addSql('DROP TABLE material.tipos_armas');
        $this->addSql('DROP TABLE material.tipo_material');
        $this->addSql('DROP TABLE cautela.tipos_cautela');
        $this->addSql('DROP TABLE material.modelos_armas');
        $this->addSql('DROP TABLE cautela.acoes_cautela');
        $this->addSql('DROP TABLE material.item_arma');
        $this->addSql('DROP TABLE pessoal.escolaridades');
        $this->addSql('DROP TABLE geral.setores');
        $this->addSql('DROP TABLE pessoal.usuarios');
        $this->addSql('DROP TABLE cautela.status_cautela');
        $this->addSql('DROP TABLE material.marcas_armas');
        $this->addSql('DROP TABLE material.coletes');
        $this->addSql('DROP TABLE material.algemas');
        $this->addSql('DROP TABLE material.destinos_material');
        $this->addSql('DROP TABLE geral.unidades');
        $this->addSql('DROP TABLE cautela.itens_cautela');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SCHEMA material');
        $this->addSql('CREATE SCHEMA pessoal');
        $this->addSql('CREATE SCHEMA cautela');
        $this->addSql('CREATE SCHEMA geral');
        $this->addSql('DROP SEQUENCE almoxarifado.produtos_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE message_seq INCREMENT BY 1 MINVALUE 3 START 3');
        $this->addSql('CREATE SEQUENCE usuarios_id_seq INCREMENT BY 1 MINVALUE 14822 START 14822');
        $this->addSql('CREATE SEQUENCE material.materiais_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.celulares_funcionais_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.radios_ht_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.municoes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.impressoras_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.calibre_armas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.talonarios_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.acessorios_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.notebooks_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.etilometros_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.destinos_material_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.status_material_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.armas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.tipo_material_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.tipos_armas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.item_arma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.tipos_colete_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.modelos_armas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.coletes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.marcas_armas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE material.algemas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.situacoes_policiais_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.faltas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.sexos_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.permissoes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.justificativas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.graduacoes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.frequencias_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.tipos_sanguineos_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.estados_civis_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.contatos_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.escolaridades_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pessoal.profiles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cautela.cautelas_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cautela.itens_cautela_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cautela.historicos_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE geral.comandos_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE geral.setores_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE geral.unidades_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE material.celulares_funcionais (id INT NOT NULL, status INT DEFAULT NULL, destino INT DEFAULT NULL, unidade INT DEFAULT NULL, tipo_material INT DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, modelo VARCHAR(255) DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, imei VARCHAR(255) DEFAULT NULL, acesso VARCHAR(255) DEFAULT NULL, origem VARCHAR(255) DEFAULT NULL, observacao TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(13) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_42dae5da7b00651c ON material.celulares_funcionais (status)');
        $this->addSql('CREATE INDEX idx_42dae5daaa7b2f5c ON material.celulares_funcionais (tipo_material)');
        $this->addSql('CREATE INDEX idx_42dae5da81f64efa ON material.celulares_funcionais (destino)');
        $this->addSql('CREATE INDEX idx_42dae5da44f8a1d3 ON material.celulares_funcionais (unidade)');
        $this->addSql('CREATE TABLE pessoal.situacoes_policiais (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.radios_ht (id INT NOT NULL, status INT DEFAULT NULL, destino INT DEFAULT NULL, unidade INT DEFAULT NULL, tipo_material INT DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, modelo VARCHAR(255) DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, tombo VARCHAR(255) DEFAULT NULL, procedencia VARCHAR(255) DEFAULT NULL, origem VARCHAR(255) DEFAULT NULL, barcode VARCHAR(13) DEFAULT NULL, observacao TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_aa4e4f1381f64efa ON material.radios_ht (destino)');
        $this->addSql('CREATE INDEX idx_aa4e4f137b00651c ON material.radios_ht (status)');
        $this->addSql('CREATE INDEX idx_aa4e4f1344f8a1d3 ON material.radios_ht (unidade)');
        $this->addSql('CREATE INDEX idx_aa4e4f13aa7b2f5c ON material.radios_ht (tipo_material)');
        $this->addSql('CREATE TABLE cautela.cautelas (id INT NOT NULL, tipo_cautela_id INT DEFAULT NULL, policial_id INT DEFAULT NULL, usuario_id INT DEFAULT NULL, status_cautela_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_validade TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, observacao TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_51987be8db38439e ON cautela.cautelas (usuario_id)');
        $this->addSql('CREATE INDEX idx_51987be8e132a3e7 ON cautela.cautelas (tipo_cautela_id)');
        $this->addSql('CREATE INDEX idx_51987be819bd774c ON cautela.cautelas (policial_id)');
        $this->addSql('CREATE INDEX idx_51987be871e74549 ON cautela.cautelas (status_cautela_id)');
        $this->addSql('CREATE TABLE material.municoes (id INT NOT NULL, tipo_material INT DEFAULT NULL, destino INT DEFAULT NULL, calibre VARCHAR(10) NOT NULL, cautelada INT NOT NULL, "real" INT NOT NULL, treino INT NOT NULL, capsulas INT NOT NULL, inservivel INT NOT NULL, deflagradas INT NOT NULL, descarregadas VARCHAR(255) NOT NULL, falta_justificar INT NOT NULL, observacao TEXT DEFAULT NULL, barcode VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_2cde763981f64efa ON material.municoes (destino)');
        $this->addSql('CREATE INDEX idx_2cde7639aa7b2f5c ON material.municoes (tipo_material)');
        $this->addSql('CREATE TABLE material.materiais (id INT NOT NULL, status INT DEFAULT NULL, destino INT DEFAULT NULL, unidade INT DEFAULT NULL, tipo_material INT DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, observacao TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(13) DEFAULT NULL, detalhes VARCHAR(255) DEFAULT NULL, material_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_c77516b6aa7b2f5c ON material.materiais (tipo_material)');
        $this->addSql('CREATE INDEX idx_c77516b681f64efa ON material.materiais (destino)');
        $this->addSql('CREATE INDEX idx_c77516b67b00651c ON material.materiais (status)');
        $this->addSql('CREATE INDEX idx_c77516b644f8a1d3 ON material.materiais (unidade)');
        $this->addSql('CREATE TABLE material.calibre_armas (id INT NOT NULL, descricao VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pessoal.faltas (id INT NOT NULL, created_at DATE NOT NULL, setor_id VARCHAR(255) NOT NULL, usuario_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.impressoras (id INT NOT NULL, destino INT DEFAULT NULL, status INT DEFAULT NULL, unidade INT DEFAULT NULL, tipo_material INT DEFAULT NULL, jurisdicao VARCHAR(255) DEFAULT NULL, modelo VARCHAR(255) DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, observacao TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(13) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_db29b03aa7b2f5c ON material.impressoras (tipo_material)');
        $this->addSql('CREATE INDEX idx_db29b037b00651c ON material.impressoras (status)');
        $this->addSql('CREATE INDEX idx_db29b0344f8a1d3 ON material.impressoras (unidade)');
        $this->addSql('CREATE INDEX idx_db29b0381f64efa ON material.impressoras (destino)');
        $this->addSql('CREATE TABLE material.talonarios (id INT NOT NULL, unidade INT DEFAULT NULL, destino INT DEFAULT NULL, status INT DEFAULT NULL, tipo_material INT DEFAULT NULL, jurisdicao VARCHAR(255) DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, modelo VARCHAR(255) DEFAULT NULL, imei VARCHAR(255) DEFAULT NULL, chip TEXT DEFAULT NULL, observacao TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(13) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_9e15f5b7b00651c ON material.talonarios (status)');
        $this->addSql('CREATE INDEX idx_9e15f5b44f8a1d3 ON material.talonarios (unidade)');
        $this->addSql('CREATE INDEX idx_9e15f5baa7b2f5c ON material.talonarios (tipo_material)');
        $this->addSql('CREATE INDEX idx_9e15f5b81f64efa ON material.talonarios (destino)');
        $this->addSql('CREATE TABLE pessoal.sexos (id INT NOT NULL, descricao VARCHAR(30) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.acessorios (id INT NOT NULL, destino_id INT DEFAULT NULL, unidade_id INT DEFAULT NULL, tipo_material INT DEFAULT NULL, descricao VARCHAR(255) NOT NULL, qtd_disponivel INT NOT NULL, qtd_inutilizavel INT DEFAULT NULL, observacao TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_59d97fc4edf4b99b ON material.acessorios (unidade_id)');
        $this->addSql('CREATE INDEX idx_59d97fc4aa7b2f5c ON material.acessorios (tipo_material)');
        $this->addSql('CREATE INDEX idx_59d97fc4e4360615 ON material.acessorios (destino_id)');
        $this->addSql('CREATE TABLE pessoal.permissoes (id INT NOT NULL, roles VARCHAR(255) DEFAULT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.notebooks (id INT NOT NULL, destino INT DEFAULT NULL, status INT DEFAULT NULL, unidade INT DEFAULT NULL, tipo_material INT DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, tombo VARCHAR(255) DEFAULT NULL, observacao TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(13) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_9651bf9744f8a1d3 ON material.notebooks (unidade)');
        $this->addSql('CREATE INDEX idx_9651bf97aa7b2f5c ON material.notebooks (tipo_material)');
        $this->addSql('CREATE INDEX idx_9651bf9781f64efa ON material.notebooks (destino)');
        $this->addSql('CREATE INDEX idx_9651bf977b00651c ON material.notebooks (status)');
        $this->addSql('CREATE TABLE material.etilometros (id INT NOT NULL, status INT DEFAULT NULL, destino INT DEFAULT NULL, unidade INT DEFAULT NULL, tipo_material INT DEFAULT NULL, tombo VARCHAR(255) DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, acessorios BOOLEAN NOT NULL, serie VARCHAR(255) DEFAULT NULL, observacao TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(13) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_ded6d7427b00651c ON material.etilometros (status)');
        $this->addSql('CREATE INDEX idx_ded6d742aa7b2f5c ON material.etilometros (tipo_material)');
        $this->addSql('CREATE INDEX idx_ded6d74244f8a1d3 ON material.etilometros (unidade)');
        $this->addSql('CREATE INDEX idx_ded6d74281f64efa ON material.etilometros (destino)');
        $this->addSql('CREATE TABLE pessoal.frequencias (id INT NOT NULL, usuario_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, frequencia BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_259df6c0db38439e ON pessoal.frequencias (usuario_id)');
        $this->addSql('CREATE TABLE pessoal.graduacoes (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, sigla VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pessoal.justificativas (id INT NOT NULL, falta_id INT DEFAULT NULL, observacao VARCHAR(255) DEFAULT NULL, arquivo VARCHAR(255) DEFAULT NULL, status BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_f7f982c23799346e ON pessoal.justificativas (falta_id)');
        $this->addSql('CREATE TABLE geral.comandos (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, comandante VARCHAR(255) DEFAULT NULL, telefone VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pessoal.tipos_sanguineos (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pessoal.estados_civis (id INT NOT NULL, descricao VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.status_material (id INT NOT NULL, descricao VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.armas (id INT NOT NULL, status_id INT DEFAULT NULL, destino_id INT DEFAULT NULL, unidade_id INT DEFAULT NULL, tipo_material_id INT DEFAULT NULL, marca_arma_id INT DEFAULT NULL, calibre_arma_id INT DEFAULT NULL, modelo_arma_id INT DEFAULT NULL, tipo_arma_id INT DEFAULT NULL, jurisdicao VARCHAR(255) DEFAULT NULL, npmma VARCHAR(255) DEFAULT NULL, serie VARCHAR(255) NOT NULL, tombo VARCHAR(255) DEFAULT NULL, ult_conferencia VARCHAR(255) DEFAULT NULL, procedencia VARCHAR(255) NOT NULL, observacao TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(13) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_c03a91ceedf4b99b ON material.armas (unidade_id)');
        $this->addSql('CREATE INDEX idx_c03a91ce1ddc7b11 ON material.armas (modelo_arma_id)');
        $this->addSql('CREATE INDEX idx_c03a91ced62c8297 ON material.armas (tipo_material_id)');
        $this->addSql('CREATE INDEX idx_c03a91cee4360615 ON material.armas (destino_id)');
        $this->addSql('CREATE INDEX idx_c03a91ce9e862afd ON material.armas (tipo_arma_id)');
        $this->addSql('CREATE INDEX idx_c03a91ce6bf700bd ON material.armas (status_id)');
        $this->addSql('CREATE INDEX idx_c03a91cebecf282a ON material.armas (marca_arma_id)');
        $this->addSql('CREATE INDEX idx_c03a91cec415fce0 ON material.armas (calibre_arma_id)');
        $this->addSql('CREATE TABLE cautela.historicos (id INT NOT NULL, usuario_id INT DEFAULT NULL, policial_id INT DEFAULT NULL, material_id INT DEFAULT NULL, acao_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_194e14ab19bd774c ON cautela.historicos (policial_id)');
        $this->addSql('CREATE INDEX idx_194e14abe308ac6f ON cautela.historicos (material_id)');
        $this->addSql('CREATE INDEX idx_194e14abdb38439e ON cautela.historicos (usuario_id)');
        $this->addSql('CREATE INDEX idx_194e14ab60da4051 ON cautela.historicos (acao_id)');
        $this->addSql('CREATE TABLE pessoal.profiles (id INT NOT NULL, descricao VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pessoal.contatos (id INT NOT NULL, destinatario_id INT DEFAULT NULL, remetente_id INT DEFAULT NULL, assunto VARCHAR(255) NOT NULL, mensagem TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_7f1d36cbb564fbc1 ON pessoal.contatos (destinatario_id)');
        $this->addSql('CREATE INDEX idx_7f1d36cbfa0a674b ON pessoal.contatos (remetente_id)');
        $this->addSql('CREATE TABLE material.tipos_colete (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.tipos_armas (id INT NOT NULL, descricao VARCHAR(50) NOT NULL, observacao TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.tipo_material (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE cautela.tipos_cautela (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.modelos_armas (id INT NOT NULL, calibre_arma_id INT DEFAULT NULL, descricao VARCHAR(255) DEFAULT NULL, total_municao INT DEFAULT NULL, observacao TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_bf85ab38c415fce0 ON material.modelos_armas (calibre_arma_id)');
        $this->addSql('CREATE TABLE cautela.acoes_cautela (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.item_arma (id INT NOT NULL, tipo_material INT DEFAULT NULL, destino INT DEFAULT NULL, descricao VARCHAR(255) NOT NULL, barcode VARCHAR(255) DEFAULT NULL, observacao TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_f66807dd81f64efa ON material.item_arma (destino)');
        $this->addSql('CREATE INDEX idx_f66807ddaa7b2f5c ON material.item_arma (tipo_material)');
        $this->addSql('CREATE TABLE pessoal.escolaridades (id INT NOT NULL, descricao VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE geral.setores (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, sigla VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pessoal.usuarios (id INT NOT NULL, sexo_id INT DEFAULT NULL, estadocivil_id INT DEFAULT NULL, escolaridade_id INT DEFAULT NULL, id_setor INT DEFAULT NULL, id_unidade INT DEFAULT NULL, profile_id INT DEFAULT NULL, fator_rh_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, username VARCHAR(50) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, nascimento DATE DEFAULT NULL, inclusao DATE DEFAULT NULL, cep VARCHAR(255) DEFAULT NULL, numeroend VARCHAR(255) DEFAULT NULL, complementoend VARCHAR(255) DEFAULT NULL, identidade_militar VARCHAR(255) DEFAULT NULL, cpf VARCHAR(255) DEFAULT NULL, phone1 VARCHAR(255) DEFAULT NULL, phone2 VARCHAR(255) DEFAULT NULL, matricula VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, situacao_policial VARCHAR(255) DEFAULT NULL, numero VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles JSON DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, id_graduacao INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_f2f4da252b32db58 ON pessoal.usuarios (sexo_id)');
        $this->addSql('CREATE INDEX idx_f2f4da252be8a956 ON pessoal.usuarios (fator_rh_id)');
        $this->addSql('CREATE INDEX idx_f2f4da25573d749b ON pessoal.usuarios (id_graduacao)');
        $this->addSql('CREATE INDEX idx_f2f4da25ccfa12b8 ON pessoal.usuarios (profile_id)');
        $this->addSql('CREATE INDEX idx_f2f4da25e99a6e1d ON pessoal.usuarios (escolaridade_id)');
        $this->addSql('CREATE INDEX idx_f2f4da25d2d890d2 ON pessoal.usuarios (estadocivil_id)');
        $this->addSql('CREATE INDEX idx_f2f4da2595bb8cf7 ON pessoal.usuarios (id_setor)');
        $this->addSql('CREATE INDEX idx_f2f4da259a6508a3 ON pessoal.usuarios (id_unidade)');
        $this->addSql('CREATE TABLE cautela.status_cautela (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.marcas_armas (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE material.coletes (id INT NOT NULL, status INT DEFAULT NULL, unidade INT DEFAULT NULL, destino INT DEFAULT NULL, tipo_material INT DEFAULT NULL, tipo_colete INT DEFAULT NULL, marca VARCHAR(50) DEFAULT NULL, modelo VARCHAR(50) DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, origem VARCHAR(50) DEFAULT NULL, carga VARCHAR(255) DEFAULT NULL, validade DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, barcode VARCHAR(13) DEFAULT NULL, observacao TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_ddb49cbdf81ea286 ON material.coletes (tipo_colete)');
        $this->addSql('CREATE INDEX idx_ddb49cbdaa7b2f5c ON material.coletes (tipo_material)');
        $this->addSql('CREATE INDEX idx_ddb49cbd81f64efa ON material.coletes (destino)');
        $this->addSql('CREATE INDEX idx_ddb49cbd44f8a1d3 ON material.coletes (unidade)');
        $this->addSql('CREATE INDEX idx_ddb49cbd7b00651c ON material.coletes (status)');
        $this->addSql('CREATE TABLE material.algemas (id INT NOT NULL, status_id INT DEFAULT NULL, destino_id INT DEFAULT NULL, unidade_id INT DEFAULT NULL, tipo_material_id INT DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, acabamento VARCHAR(255) DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, tombo VARCHAR(255) DEFAULT NULL, carga VARCHAR(100) DEFAULT NULL, observacao TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, barcode VARCHAR(13) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_ccf493d06bf700bd ON material.algemas (status_id)');
        $this->addSql('CREATE INDEX idx_ccf493d0edf4b99b ON material.algemas (unidade_id)');
        $this->addSql('CREATE INDEX idx_ccf493d0d62c8297 ON material.algemas (tipo_material_id)');
        $this->addSql('CREATE INDEX idx_ccf493d0e4360615 ON material.algemas (destino_id)');
        $this->addSql('CREATE TABLE material.destinos_material (id INT NOT NULL, descricao VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE geral.unidades (id INT NOT NULL, comando_id INT DEFAULT NULL, descricao VARCHAR(255) NOT NULL, sigla VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_9206b59298a62f9b ON geral.unidades (comando_id)');
        $this->addSql('CREATE TABLE cautela.itens_cautela (id INT NOT NULL, cautela_id INT DEFAULT NULL, material_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_devolucao TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, quantidade INT DEFAULT NULL, devolvido BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_671109e570b4a1cf ON cautela.itens_cautela (cautela_id)');
        $this->addSql('CREATE INDEX idx_671109e5e308ac6f ON cautela.itens_cautela (material_id)');
        $this->addSql('ALTER TABLE material.celulares_funcionais ADD CONSTRAINT fk_42dae5da7b00651c FOREIGN KEY (status) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.celulares_funcionais ADD CONSTRAINT fk_42dae5da81f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.celulares_funcionais ADD CONSTRAINT fk_42dae5da44f8a1d3 FOREIGN KEY (unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.celulares_funcionais ADD CONSTRAINT fk_42dae5daaa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.radios_ht ADD CONSTRAINT fk_aa4e4f137b00651c FOREIGN KEY (status) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.radios_ht ADD CONSTRAINT fk_aa4e4f1381f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.radios_ht ADD CONSTRAINT fk_aa4e4f1344f8a1d3 FOREIGN KEY (unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.radios_ht ADD CONSTRAINT fk_aa4e4f13aa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.cautelas ADD CONSTRAINT fk_51987be8e132a3e7 FOREIGN KEY (tipo_cautela_id) REFERENCES cautela.tipos_cautela (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.cautelas ADD CONSTRAINT fk_51987be819bd774c FOREIGN KEY (policial_id) REFERENCES pessoal.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.cautelas ADD CONSTRAINT fk_51987be8db38439e FOREIGN KEY (usuario_id) REFERENCES pessoal.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.cautelas ADD CONSTRAINT fk_51987be871e74549 FOREIGN KEY (status_cautela_id) REFERENCES cautela.status_cautela (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.municoes ADD CONSTRAINT fk_2cde7639aa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.municoes ADD CONSTRAINT fk_2cde763981f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.materiais ADD CONSTRAINT fk_c77516b67b00651c FOREIGN KEY (status) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.materiais ADD CONSTRAINT fk_c77516b681f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.materiais ADD CONSTRAINT fk_c77516b644f8a1d3 FOREIGN KEY (unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.materiais ADD CONSTRAINT fk_c77516b6aa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.impressoras ADD CONSTRAINT fk_db29b0381f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.impressoras ADD CONSTRAINT fk_db29b037b00651c FOREIGN KEY (status) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.impressoras ADD CONSTRAINT fk_db29b0344f8a1d3 FOREIGN KEY (unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.impressoras ADD CONSTRAINT fk_db29b03aa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.talonarios ADD CONSTRAINT fk_9e15f5b44f8a1d3 FOREIGN KEY (unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.talonarios ADD CONSTRAINT fk_9e15f5b81f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.talonarios ADD CONSTRAINT fk_9e15f5b7b00651c FOREIGN KEY (status) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.talonarios ADD CONSTRAINT fk_9e15f5baa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.acessorios ADD CONSTRAINT fk_59d97fc4e4360615 FOREIGN KEY (destino_id) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.acessorios ADD CONSTRAINT fk_59d97fc4edf4b99b FOREIGN KEY (unidade_id) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.acessorios ADD CONSTRAINT fk_59d97fc4aa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.notebooks ADD CONSTRAINT fk_9651bf9781f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.notebooks ADD CONSTRAINT fk_9651bf977b00651c FOREIGN KEY (status) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.notebooks ADD CONSTRAINT fk_9651bf9744f8a1d3 FOREIGN KEY (unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.notebooks ADD CONSTRAINT fk_9651bf97aa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.etilometros ADD CONSTRAINT fk_ded6d7427b00651c FOREIGN KEY (status) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.etilometros ADD CONSTRAINT fk_ded6d74281f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.etilometros ADD CONSTRAINT fk_ded6d74244f8a1d3 FOREIGN KEY (unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.etilometros ADD CONSTRAINT fk_ded6d742aa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.frequencias ADD CONSTRAINT fk_259df6c0db38439e FOREIGN KEY (usuario_id) REFERENCES pessoal.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.justificativas ADD CONSTRAINT fk_f7f982c23799346e FOREIGN KEY (falta_id) REFERENCES pessoal.faltas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.armas ADD CONSTRAINT fk_c03a91ce6bf700bd FOREIGN KEY (status_id) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.armas ADD CONSTRAINT fk_c03a91cee4360615 FOREIGN KEY (destino_id) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.armas ADD CONSTRAINT fk_c03a91ceedf4b99b FOREIGN KEY (unidade_id) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.armas ADD CONSTRAINT fk_c03a91ced62c8297 FOREIGN KEY (tipo_material_id) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.armas ADD CONSTRAINT fk_c03a91cebecf282a FOREIGN KEY (marca_arma_id) REFERENCES material.marcas_armas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.armas ADD CONSTRAINT fk_c03a91cec415fce0 FOREIGN KEY (calibre_arma_id) REFERENCES material.calibre_armas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.armas ADD CONSTRAINT fk_c03a91ce1ddc7b11 FOREIGN KEY (modelo_arma_id) REFERENCES material.modelos_armas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.armas ADD CONSTRAINT fk_c03a91ce9e862afd FOREIGN KEY (tipo_arma_id) REFERENCES material.tipos_armas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.historicos ADD CONSTRAINT fk_194e14abdb38439e FOREIGN KEY (usuario_id) REFERENCES pessoal.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.historicos ADD CONSTRAINT fk_194e14ab19bd774c FOREIGN KEY (policial_id) REFERENCES pessoal.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.historicos ADD CONSTRAINT fk_194e14abe308ac6f FOREIGN KEY (material_id) REFERENCES material.materiais (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.historicos ADD CONSTRAINT fk_194e14ab60da4051 FOREIGN KEY (acao_id) REFERENCES cautela.acoes_cautela (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.contatos ADD CONSTRAINT fk_7f1d36cbb564fbc1 FOREIGN KEY (destinatario_id) REFERENCES pessoal.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.contatos ADD CONSTRAINT fk_7f1d36cbfa0a674b FOREIGN KEY (remetente_id) REFERENCES pessoal.usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.modelos_armas ADD CONSTRAINT fk_bf85ab38c415fce0 FOREIGN KEY (calibre_arma_id) REFERENCES material.calibre_armas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.item_arma ADD CONSTRAINT fk_f66807ddaa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.item_arma ADD CONSTRAINT fk_f66807dd81f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.usuarios ADD CONSTRAINT fk_f2f4da252b32db58 FOREIGN KEY (sexo_id) REFERENCES pessoal.sexos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.usuarios ADD CONSTRAINT fk_f2f4da25d2d890d2 FOREIGN KEY (estadocivil_id) REFERENCES pessoal.estados_civis (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.usuarios ADD CONSTRAINT fk_f2f4da25e99a6e1d FOREIGN KEY (escolaridade_id) REFERENCES pessoal.escolaridades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.usuarios ADD CONSTRAINT fk_f2f4da2595bb8cf7 FOREIGN KEY (id_setor) REFERENCES geral.setores (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.usuarios ADD CONSTRAINT fk_f2f4da259a6508a3 FOREIGN KEY (id_unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.usuarios ADD CONSTRAINT fk_f2f4da25ccfa12b8 FOREIGN KEY (profile_id) REFERENCES pessoal.profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoal.usuarios ADD CONSTRAINT fk_f2f4da252be8a956 FOREIGN KEY (fator_rh_id) REFERENCES pessoal.tipos_sanguineos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.coletes ADD CONSTRAINT fk_ddb49cbd7b00651c FOREIGN KEY (status) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.coletes ADD CONSTRAINT fk_ddb49cbd44f8a1d3 FOREIGN KEY (unidade) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.coletes ADD CONSTRAINT fk_ddb49cbd81f64efa FOREIGN KEY (destino) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.coletes ADD CONSTRAINT fk_ddb49cbdaa7b2f5c FOREIGN KEY (tipo_material) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.coletes ADD CONSTRAINT fk_ddb49cbdf81ea286 FOREIGN KEY (tipo_colete) REFERENCES material.tipos_colete (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.algemas ADD CONSTRAINT fk_ccf493d06bf700bd FOREIGN KEY (status_id) REFERENCES material.status_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.algemas ADD CONSTRAINT fk_ccf493d0e4360615 FOREIGN KEY (destino_id) REFERENCES material.destinos_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.algemas ADD CONSTRAINT fk_ccf493d0edf4b99b FOREIGN KEY (unidade_id) REFERENCES geral.unidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material.algemas ADD CONSTRAINT fk_ccf493d0d62c8297 FOREIGN KEY (tipo_material_id) REFERENCES material.tipo_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE geral.unidades ADD CONSTRAINT fk_9206b59298a62f9b FOREIGN KEY (comando_id) REFERENCES geral.comandos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.itens_cautela ADD CONSTRAINT fk_671109e570b4a1cf FOREIGN KEY (cautela_id) REFERENCES cautela.cautelas (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cautela.itens_cautela ADD CONSTRAINT fk_671109e5e308ac6f FOREIGN KEY (material_id) REFERENCES material.materiais (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE almoxarifado.produtos');
    }
}
